name: Docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      - name: Build and push database
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .docker/Dockerfile.database
          tags: onomy/aurora-relayer-database:latest,onomy/aurora-relayer-database:v-${{ steps.buildnumber.outputs.build_number }}

      - name: Build and push endpoint
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .docker/Dockerfile.endpoint
          tags: onomy/aurora-relayer-endpoint:latest,onomy/aurora-relayer-endpoint:v-${{ steps.buildnumber.outputs.build_number }}